id: IBD6E18EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:10:50+00:00'
last_modified: '2022-06-10T05:39:47.754385+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5481
  title: མཁས་དབང་ཚུལ་ཁྲིམས་བློ་གྲོས་ཀྱི་བཀའ་སློབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DA46:
      image_group_id: I3CN5483
      title: Volume 1 of dus thog char pa/
      total_pages: 297
      order: 1
      base_file: DA46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
